maintainer "Amazon Web Services"
description "Deploy applications"
version "0.1"
recipe "deploy-custom::scm", "Install and setup the source code management system"
recipe "deploy-custom::rails", "Deploy a Rails application"
recipe "deploy-custom::php", "Deploy a PHP application"
recipe "deploy-custom::rails-undeploy", "Remove a Rails application"
recipe "deploy-custom::mysql", "Create the MySQL database for an app"
recipe "deploy-custom::mysql-configure", "Reconfigure the database"
recipe "deploy-custom::logrotate", "Logrotate configuration for log files in shared/log/"

depends "dependencies"
depends "apache2"
depends "mod_php5_apache2"
depends "nginx"
depends "ssh_users"
depends "opsworks_agent_monit"
depends "passenger_apache2"
depends "unicorn"
depends "rainbows"
